### ISSUE TITLE
Don't highlight when there are no other matches

### ISSUE THREAD

**Issue by xanderdunn** [qstrahl/vim-matchmaker#15]
Many thanks for this great plugin!  It does for me what most GUI IDEs do, and it doesn't even interfere with vim's search highlighting.  

It would be nice if there were an option to disable highlighting when there are no matches to the word under the cursor.  It seems unnecessary to highlight the word under the cursor if there is nothing else to highlight.  

Thanks!

**Comment by qstrahl** [comment]
Good idea! I'll look into that

**Comment by qstrahl** [comment]
Hey @xanderdunn! This is now possible as of a0b27f3c4fa9ab9d50b9a2823f1e9d305650fee3 - all you have to do is add `let g:matchmaker_ignore_single_match = 1` to your vimrc
