### ISSUE TITLE
Overriding highlight group does not work (in neovim?)

### ISSUE THREAD

**Issue by rompetroll** [qstrahl/vim-matchmaker#20]
My understanding is that it should be possible to customize the highlight colors for matchmaker by adding something like `highlight Matchmaker guibg=yellow guifg=black` to the vim config before the plugin is loaded. However, I cannot get this to work i my neovim setup. It seems like changes to the highlight group only are effective if done inside of the plugin file.

I have no clue why that is. Could be because of other plugins, my gruvbox colorscheme, a neovim thing, ... .

My current solution is this:
https://github.com/qstrahl/vim-matchmaker/compare/master...rompetroll:master

With this new variable, the plugin will link the Matchmaker highlight group to a different group. Example usage:

`let g:matchmaker_hl_group='underlined'`

Now, while this works, I would prefer if I could set `highlight link Matchmaker underlined` in my user config instead.

**Comment by qstrahl** [comment]
Hmmm... what does `verbose highlight Matchmaker` tell you, in the case where it doesn't work as you expect?

**Comment by rompetroll** [comment]
Thanks for following this up, I had totally forgotten.

Apparently this works now. I removed my custom config and just set `highlight link Matchmaker underlined`, and matches are underlined!

![matchmaker-works](https://cloud.githubusercontent.com/assets/674691/25744115/7acc4d5e-3198-11e7-84e1-0fc8ee03736c.png)
